channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - networkx
  - scipy
  - scikit-learn
  - notebook
  - xlrd
  - openpyxl
  - xlsxwriter
  - geopandas
  - shapely
  - pyproj
  - geopy
  - geojson
  - osmnx
  - matplotlib
  - tqdm
  - numba
  - pip:
    - gtfs_kit
    - ray
