channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas<=2.1
  - networkx
  - scipy
  - scikit-learn
  - notebook
  - xlrd
  - openpyxl
  - geopandas
  - shapely
  - pyproj
  - geopy
  - matplotlib
  - tqdm
